config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  #resources :bulletins, except: [:index] if we want to put bulletins by themselves

  get "contact", to: "pages#contact"
  get "about", to: "pages#about"
  get "error", to: "pages#error"

  get "twitter", to: redirect("https://twitter.com/csleisz")

  resources :partners do
    resources :bulletins, except: [:index], controller: 'partners/bulletins'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'

  get "*path", to: redirect("/error")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bulletin.rb
class Bulletin < ApplicationRecord
	#include ImageUploader[:image]

  belongs_to :partner

  #validates :description, presence: true

end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/partner.rb
class Partner < ApplicationRecord
	has_many :bulletins
	after_initialize :set_defaults

	validates_presence_of :name, :description
	#assuming we have a "game tag for partners"
	#scope :destiny, -> {where(game = "destiny")}
	#scope :arms, -> {where(game = "arms")}

	def set_defaults
		self.metaname ||= "none"
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end

  def about
  	@title = "This is my very cool page"
  end

  def home
  	@partners = Partner.all
  end

  def error
  	
  end
end

app/controllers/partners/bulletins_controller.rb
class Partners::BulletinsController < ApplicationController
  before_action :set_bulletin, only: [:show, :edit, :update, :destroy]
  before_action :set_partner, only: [:show, :new, :edit, :create, :update, :destroy]
  def show
  end

  def new
    @bulletin = Bulletin.new
  end

  def edit
  end

  def create
    @bulletin = Bulletin.new(bulletin_params)
    @bulletin.partner_id = @partner.id

    respond_to do |format|
      if @bulletin.save
        format.html { redirect_to partner_url(@bulletin.partner_id), notice: "Bulletin was created succesfully!"}
        format.json { render :show, status: :created, location: @bulletin }
      else
        format.html { render :new }
        format.json { render json: @bulletin.errors, status: :unprocessable_entity }
    end
  end
end

  def update
    respond_to do |format|
      if @bulletin.update(bulletin_params)
        format.html { redirect_to partner_url(@bulletin.partner_id), notice: "Bulletin was updated succesfully!"}
        format.json { render :show, status: :created, location: @bulletin }
      else
        format.html { render :edit }
        format.json { render json: @bulletin.errors, status: :unprocessable_entity }
    end
  end
end

def destroy
  @bulletin.destroy
  respond_to do |format|
    format.html { redirect_to partner_url(@bulletin.partner_id), notice: "Bulletin was destroyed succesfully!"}
    format.json { head :no_content }
  end
end

private

  def set_bulletin
    @bulletin = Bulletin.find(params[:id])
  end

  def set_partner
    @partner = Partner.find(params[:partner_id])
  end

  def bulletin_params
    params.require(:bulletin).permit(:name, :description, :partner_id, :bulletin_file)
  end
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  before_action :set_partner, only: [:show, :edit, :update, :destroy]

  # GET /partners
  # GET /partners.json
  def index
    @partners = Partner.all
  end

  # GET /partners/1
  # GET /partners/1.json
  def show
    @bulletins = @partner.bulletins
  end

  # GET /partners/new
  def new
    @partner = Partner.new
  end

  # GET /partners/1/edit
  def edit
  end

  # POST /partners
  # POST /partners.json
  def create
    @partner = Partner.new(partner_params)

    respond_to do |format|
      if @partner.save
        format.html { redirect_to @partner, notice: 'Awesome! A new partner is breaking the meta.' }
        format.json { render :show, status: :created, location: @partner }
      else
        format.html { render :new }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /partners/1
  # PATCH/PUT /partners/1.json
  def update
    respond_to do |format|
      if @partner.update(partner_params)
        format.html { redirect_to @partner, notice: 'Partner was successfully updated.' }
        format.json { render :show, status: :ok, location: @partner }
      else
        format.html { render :edit }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /partners/1
  # DELETE /partners/1.json
  def destroy
    @partner.destroy
    respond_to do |format|
      format.html { redirect_to partners_url, notice: 'Partner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_partner
      @partner = Partner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def partner_params
      params.require(:partner).permit(:name, :description, :metaname)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bulletins_helper.rb
module BulletinsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Breakthemeta</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
  	<%= render 'shared/nav' %>
    <%= render 'shared/alerts' %>

    <div class="row collapse">
      <div class="small-12 small-centered medium-8 medium-centered large-5 large-centered columns">
        <%= yield %>
      </div>
    </div>

    <%= render 'shared/footer' %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<hr>
<p><%= @title %></p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/error.html.erb
<h1>Sorry, that page does not exist</h1>

Go back to <%= link_to "homepage", root_path %>

app/views/pages/home.html.erb
<h2>Naisu News</h2>

<div class= "homepage-partners">
	<%= render "shared/partners" %>
</div>

app/views/partners/_form.html.erb
<%= form_for(partner) do |f| %>
  <% if partner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(partner.errors.count, "error") %> prohibited this partner from being saved:</h2>

      <ul>
      <% partner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

    <div class="field">
    <%= f.label :metaname %>
    <%= f.text_area :metaname %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/partners/bulletins/_form.html.erb
<%= form_for [@partner, @bulletin] do |f| %>
  <% if @bulletin.errors.any? %>
  	<%= pluralize(@bulletin.errors.count, "error") %> prohibited this bulletin from being saved:

  	<% @bulletin.errors.full_messages.each do |message| %>
  	  <%= message %>
  	<% end %>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.submit %>

 <% end %>

app/views/partners/bulletins/edit.html.erb
<%= render 'form' %>

app/views/partners/bulletins/new.html.erb
<%= render 'form' %>

app/views/partners/bulletins/show.html.erb
<hr>

<h3><%= @bulletin.name %></h3>

<p><%= @bulletin.description %></p>

<h4>Bulletin created at: <%= @bulletin.created_at %></h4>

<% if @bulletin.created_at != @bulletin.updated_at %>
  <h4> Bulletin updated at: <%= @bulletin.updated_at %></h4>
<% end %>

<%= link_to "Edit", edit_partner_bulletin_path(@bulletin.partner_id, @bulletin.id) %>

<%= link_to "Back to Partners", partner_path(@bulletin.partner_id) %>

app/views/partners/edit.html.erb
<h1>Editing Partner</h1>

<%= render 'form', partner: @partner %>

<%= link_to 'Show', @partner %> |
<%= link_to 'Back', partners_path %>

app/views/partners/index.html.erb
<h2 class="page-title">Partners</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Metaname</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @partners.each do |partner| %>
      <tr>
        <td><%= link_to partner.name, partner, class: "row"%></td>
        <td><%= partner.description %></td>
        <td><%= partner.metaname %></td>
        <td><%= link_to 'Show', partner %></td>
        <td><%= link_to 'Edit', edit_partner_path(partner) %></td>
        <td><%= link_to 'Destroy', partner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<br>

<%= link_to 'New Partner', new_partner_path %>

app/views/partners/new.html.erb
<h1>New Partner</h1>

<%= render 'form', partner: @partner %>

<%= link_to 'Back', partners_path %>

app/views/partners/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <strong><%= @partner.name %>'s Page</strong>
</h2>

<p>
  <strong>Description:</strong>
  <%= @partner.description %>
</p>

<p>
  <strong>Metaname:</strong>
  <%= @partner.metaname %>
</p>
<%= link_to 'Edit', edit_partner_path(@partner) %> |
<%= link_to 'Back', partners_path %>

<hr>

<h2>Featured Posts from <%= @partner.name %></h2>

<% @bulletins.each do |bulletin| %>

  <p><%= link_to bulletin.name, partner_bulletin_path(@partner.id, bulletin.id) %></p>

<% end %>

<%= link_to "Add a new Bulletin for this Partner", new_partner_bulletin_path(partner_id: @partner.id) %>

app/views/shared/_alerts.html.erb
  <% flash.each do |type, message| %>
    <div class="flash alert-box text-center <%= type %>">
      <%= message %>
      <a href='#' class='close'>&times;</a>
    </div>
  <% end %>

app/views/shared/_nav.html.erb
<header class="row global-header">
  <div class="small-12 small-centered medium-8 medium-centered large-5 large-centered columns">
    <%= link_to "Home", root_path %>
    <%= link_to "Partners", partners_path %>
    <%= link_to "About", about_path %>
    <%= link_to "Contact", contact_path %>
    
    <% if current_user %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      <%= link_to "Edit Account", edit_user_registration_path %>

    <% else %>
      <%= link_to "Register", new_user_registration_path %>
      <%= link_to "Sign In", new_user_session_path %>
    <% end %>
  </div>
  <hr>
</header>


 

app/views/shared/_partners.html.erb
<% @partners.each do |partner| %>
  
  <p><strong><%= partner.name %></strong> - <%= partner.description %> - - <%= partner.metaname %></p>

<% end %>